# Generated by Django 4.1.1 on 2023-01-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
